name: python pipeline

on: [push]

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - run: python.py
 
 build:
  needs: [test]
  runs-on: windows-latest
   steps:
   - uses: actions/checkout@v2
     uses: actions/uploadartifact@v2
     with:
     name: hello
     path: .
     
   
  
